### ISSUE TITLE
No lyrics found

### ISSUE THREAD

**Issue by LackyPal** [vookav2/songlyrics#1]
The package was working fine some days ago. But now getting `No lyrics found!`. I have tested with many songs name, but getting the same error. I also tried with the example song name `breezeblocks`, same error. This is a great library, please fix this ASAP

**Comment by mr687** [comment]
Hi @L0SER8228,

Please check [the latest version](https://www.npmjs.com/package/songlyrics?activeTab=versions). Hope this can be fixed.

or you just run `yarn add songlyrics` to install the latest version directly.
