### ISSUE TITLE
lyrics from "www.azlyrics.com" appear as an empty string

### ISSUE THREAD

**Issue by GlxryX** [vookav2/songlyrics#14]
this is the response to `await songlyrics(Whats Poppin (feat. DaBaby, Tory Lanez & Lil Wayne) (Remix) (Bonus Track)])`
```
{
  title: 'Jack Harlow - WHATS POPPIN (Remix) Lyrics',
  lyrics: '',
  source: {
    name: 'AZLyrics',
    url: 'www.azlyrics.com',
    link: 'https://www.azlyrics.com/lyrics/jackharlow/whatspoppinremix.html'
  }
}
```

**Comment by mr687** [comment]
Hi @GlxryX , the result is not always as expected. I suggest you can normalize your query first, for ex:
`Whats Poppin (feat. DaBaby, Tory Lanez & Lil Wayne) (Remix) (Bonus Track)]` to: `Whats Popping`

or just return `Lyrics Not Found` in your app if the result is empty.

anyway I just tried with the same query and the result is expexted.

![image](https://user-images.githubusercontent.com/26916086/181290497-0c4af0d1-a262-4472-a28d-43c692679a05.png)

**Comment by GlxryX** [comment]
That interesting. One issue is that the song you've shown isn't the remix version that I get from the link in my response. I'm assuming it's because your response is from a different source. As for "normalizing" my query, it already is so I'm guessing that's what was causing the issue to arise in the first place. Regardless, the response is clearly there but does not appear in the response. Could it be possible it's just an issue with web scrapping from that site in particular?
