### ISSUE TITLE
AZLyrics returns unaccurate results,.

### ISSUE THREAD

**Issue by TehPig** [vookav2/songlyrics#19]
Hey there,

I have tried searching for some song lyrics but for some reason it returns wrong results.
The source that is selected all the time is AZLyrics.
[Here is a screenshot](https://i.imgur.com/MMFdjrv.png)

Using the package on a completely empty Visual Studio Code node.js project with the same request returns the information properly, but the source is from Genius instead.

I am using the latest version of the package, `v2.4.4`.
Is there any way to solve this?

**Comment by Eithoo** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/62159998/188924474-58f626db-18a4-4a9d-8808-dfde1008b6e0.png)
Normalize your query.

**Comment by TehPig** [comment]
Query is the exact same as the one provided in your screenshot.
How does the package select the source of the lyrics?

**Comment by TehPig** [comment]
Query: `neffex unstoppable`
Output
```js
{
  title: 'NEFFEX - Unstoppable Lyrics',
  lyrics: 'undefined',
  source: {
    name: 'AZLyrics',
    url: 'www.azlyrics.com',
    link: 'https://www.azlyrics.com/lyrics/neffex/unstoppable.html'
  }
}
```

And here is another query: `neffex first time`
Output
```js
Error: Failed to get the response: 403
```

**Comment by Eithoo** [comment]
> Query is the exact same as the one provided in your screenshot. How does the package select the source of the lyrics?

@TehPigYT It's searching in DuckDuckGo for lyrics and returns the first result from sources (AZLyrics, Genius, Lyrics, Musixmatch)

**Comment by Eithoo** [comment]
Maybe AZLyrics is blocked in your country by ISP? You can try with a VPN to find out if that's the issue.

**Comment by TehPig** [comment]
But why is it searching for AZLyrics on the host that I use and uses Genius when I use the package locally?
With the same exact query.

I have also tried using it on another host with a different server location and it is still showing 403 errors.

**Comment by TehPig** [comment]
Is there a chance that there might be a future where we can select the source of the lyrics, along with request parameters?

**Comment by mr687** [comment]
> Hey there,
> 
> I have tried searching for some song lyrics but for some reason it returns wrong results. The source that is selected all the time is AZLyrics. [Here is a screenshot](https://i.imgur.com/MMFdjrv.png)
> 
> Using the package on a completely empty Visual Studio Code node.js project with the same request returns the information properly, but the source is from Genius instead.
> 
> I am using the latest version of the package, `v2.4.4`. Is there any way to solve this?

Hi @TehPigYT, sorry for late response. you can upgrade the package version to `v2.4.5`. Thanks
