### ISSUE TITLE
Ability to search with the song artists' names for better lyrics accuracy.

### ISSUE THREAD

**Issue by Sandakan** [vookav2/songlyrics#6]
**FEATURE REQUREST**

Sometimes when I try to fetch lyrics from this package, it gives non-relevant lyrics to the song. I think this happens because there are many songs with the same name. Maybe adding an optional parameter to specify the artists' names can improve the accuracy of the results.

**Comment by mr687** [comment]
Hi @Sandakan,

Have you tried to input the artist name along with the title? so the query format can be like `{title} {artist's name}`.

```ts
songlyrics('breezeblocks alt j')
  .then(lyrics => console.log(lyrics))
  .catch(console.warn)
```

Thanks for reminds me with this issue, I will be updating the readme to include more usage examples.

**Comment by mr687** [comment]
Hi @Sandakan,

Please check [the latest version](https://www.npmjs.com/package/songlyrics?activeTab=versions). Hope this can be fixed.

or you just run `yarn add songlyrics` to install the latest version directly.

**Comment by Sandakan** [comment]
@mr687,

Thanks for your help. It really improved the accuracy of the results.
