### ISSUE TITLE
Unwanted lyrics (sometimes)

### ISSUE THREAD

**Issue by benjaminaarsen** [vookav2/songlyrics#9]
I have tried your API for a while and it is working pretty well. Sometimes though it doesn't work as I hoped. For example when I use the query: "some nights", referring to the song Some Nights from 'fun.', i get lyrics for a whole different kind of song, when trying to type the band after it it doesn't give me the required lyrics either. Is there anything you can do to fix this issue (maybe take the first result that comes up so you get the most popular one?)

Thanks in advance :)

**Comment by mr687** [comment]
Hi @benjaminaarsen,

Please check [the latest version](https://www.npmjs.com/package/songlyrics?activeTab=versions). Hope this can be fixed.

or you just run `yarn add songlyrics` to install the latest version directly.
